# Generated by Django 5.2.8 on 2025-11-05 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id_cadeira', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ocupada', 'Ocupada'), ('desocupada', 'Desocupada')], default='desocupada', max_length=10)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadeiras', to='sala.sala')),
            ],
            options={
                'db_table': 'cadeira',
            },
        ),
    ]
