# Generated by Django 5.2.8 on 2025-11-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadeira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='pos_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cadeira',
            name='pos_y',
            field=models.FloatField(default=0),
        ),
    ]
