# Generated by Django 5.2.8 on 2025-11-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='mapa_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='mapas_plantas/'),
        ),
    ]
