# Generated by Django 5.2.8 on 2025-11-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='tipo_sala',
            field=models.CharField(choices=[('estacao', 'Estação de Trabalho'), ('reuniao', 'Sala de Reunião')], default='estacao', max_length=10),
        ),
    ]
