# Generated by Django 5.2.8 on 2025-11-06 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0002_sala_tipo_sala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='status',
        ),
    ]
