# Generated by Django 5.2.8 on 2025-11-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0003_remove_sala_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='tipo_sala',
            new_name='tipo',
        ),
    ]
