# Generated by Django 5.2.8 on 2025-12-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilDePermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Perfil')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('acessoBasico', models.BooleanField(default=True, verbose_name='Acesso Básico')),
                ('dashboards', models.BooleanField(default=False, verbose_name='Dashboards')),
                ('salasReuniao', models.BooleanField(default=False, verbose_name='Salas de Reunião')),
                ('administracao', models.BooleanField(default=False, verbose_name='Administração')),
            ],
            options={
                'verbose_name': 'Perfil de Permissão',
                'verbose_name_plural': 'Perfis de Permissão',
            },
        ),
    ]
